---
language: ruby
cache: bundler
os: linux
dist: xenial
before_install: gem install bundler -v 2.1.4
script:
- bundle exec rake rubocop
- bundle exec rake rspec
jobs:
  fast_finish: true
  include:
  - rvm: 2.7.1
